name: Frontend/Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Lint and Fix
        run: |
          cd backend
          npm run lint-fix || true

      - name: Run backend unit tests
        run: |
          cd backend
          npm test -- --exit

  frontend:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npm ci

      - name: Lint and Fix
        run: |
          cd frontend
          npm run lint-fix || true

      - name: Build frontend
        run: |
          cd frontend
          npm run build
